name: CI
on:
  push: { branches: [ "**" ] }
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo repo
        run: echo "Repo: ${{ github.repository }} | SHA: ${{ github.sha }}"